export const PermissionKeys = {
  WorkspaceAdminAccess: "workspace:admin:access",
  WorkspaceVendorAccess: "workspace:vendor:access",
  WorkspaceCustomerAccess: "workspace:customer:access",

  VendorRead: "vendor:read",
  VendorCreate: "vendor:create",
  VendorUpdateAny: "vendor:update:any",
  VendorUpdateOwn: "vendor:update:own",
  VendorDeleteAny: "vendor:delete:any",

  CategoryManage: "category:manage",
  LocationManage: "location:manage",

  PackageVendorRead: "package:vendor:read",
  PackageVendorCreateAny: "package:vendor:create:any",
  PackageVendorCreateOwn: "package:vendor:create:own",
  PackageVendorUpdateAny: "package:vendor:update:any",
  PackageVendorUpdateOwn: "package:vendor:update:own",
  PackageVendorDeleteAny: "package:vendor:delete:any",
  PackageVendorDeleteOwn: "package:vendor:delete:own",

  PackagePlatformRead: "package:platform:read",
  PackagePlatformManage: "package:platform:manage",
  PackageLeadRead: "package:lead:read",
  PackageLeadUpdate: "package:lead:update",
  PackageLeadCreate: "package:lead:create",

  AvailabilityReadOwn: "availability:read:own",
  AvailabilityReadPublic: "availability:read:public",
  AvailabilityWriteOwn: "availability:write:own",
  AvailabilityWriteAny: "availability:write:any",

  BookingReadOwnCustomer: "booking:read:own:customer",
  BookingReadOwnVendor: "booking:read:own:vendor",
  BookingReadAny: "booking:read:any",
  BookingCreate: "booking:create",
  BookingUpdateOwnVendor: "booking:update:own:vendor",
  BookingUpdateAny: "booking:update:any",

  LeadReadOwnVendor: "lead:read:own:vendor",
  LeadReadAny: "lead:read:any",
  LeadCreate: "lead:create",
  LeadUpdateOwnVendor: "lead:update:own:vendor",
  LeadUpdateAny: "lead:update:any",
  LeadConvertOwnVendor: "lead:convert:own:vendor",
  LeadConvertAny: "lead:convert:any",

  GalleryRead: "gallery:read",
  GalleryWrite: "gallery:write",

  UploadImage: "upload:image",

  UserProfileRead: "user:profile:read",
  UserProfileUpdate: "user:profile:update",
  UserSystemRead: "user:system:read",
  UserSystemCreate: "user:system:create",

  ScopeVendorOwn: "scope:vendor:own",
  ScopeCustomerOwn: "scope:customer:own",
} as const;

export type PermissionKey = (typeof PermissionKeys)[keyof typeof PermissionKeys];

export const DefaultLandingByPermissionPriority: Array<{ permission: PermissionKey; path: string }> = [
  { permission: PermissionKeys.WorkspaceAdminAccess, path: "/admin" },
  { permission: PermissionKeys.WorkspaceVendorAccess, path: "/vendor" },
  { permission: PermissionKeys.WorkspaceCustomerAccess, path: "/" },
];

export const SystemRoleKeys = {
  SuperAdmin: "super_admin",
  VendorAdmin: "vendor_admin",
  AccountsAdmin: "accounts_admin",
  Vendor: "vendor",
  Customer: "customer",
} as const;

export const DefaultRolePermissionKeys: Record<string, PermissionKey[]> = {
  [SystemRoleKeys.SuperAdmin]: Object.values(PermissionKeys),
  [SystemRoleKeys.VendorAdmin]: [
    PermissionKeys.WorkspaceAdminAccess,
    PermissionKeys.VendorRead,
    PermissionKeys.VendorUpdateAny,
    PermissionKeys.CategoryManage,
    PermissionKeys.LocationManage,
    PermissionKeys.PackageVendorRead,
    PermissionKeys.PackageVendorCreateAny,
    PermissionKeys.PackageVendorUpdateAny,
    PermissionKeys.PackageVendorDeleteAny,
    PermissionKeys.PackagePlatformRead,
    PermissionKeys.PackagePlatformManage,
    PermissionKeys.PackageLeadRead,
    PermissionKeys.PackageLeadUpdate,
    PermissionKeys.LeadReadAny,
    PermissionKeys.LeadUpdateAny,
    PermissionKeys.LeadConvertAny,
    PermissionKeys.BookingReadAny,
    PermissionKeys.BookingUpdateAny,
    PermissionKeys.AvailabilityWriteAny,
    PermissionKeys.AvailabilityReadPublic,
    PermissionKeys.GalleryRead,
    PermissionKeys.GalleryWrite,
    PermissionKeys.UploadImage,
    PermissionKeys.UserProfileRead,
    PermissionKeys.UserProfileUpdate,
  ],
  [SystemRoleKeys.AccountsAdmin]: [
    PermissionKeys.WorkspaceAdminAccess,
    PermissionKeys.VendorRead,
    PermissionKeys.VendorUpdateAny,
    PermissionKeys.LocationManage,
    PermissionKeys.PackageVendorRead,
    PermissionKeys.PackageVendorCreateAny,
    PermissionKeys.PackageVendorUpdateAny,
    PermissionKeys.PackageVendorDeleteAny,
    PermissionKeys.PackagePlatformRead,
    PermissionKeys.PackagePlatformManage,
    PermissionKeys.PackageLeadRead,
    PermissionKeys.PackageLeadUpdate,
    PermissionKeys.LeadReadAny,
    PermissionKeys.LeadUpdateAny,
    PermissionKeys.LeadConvertAny,
    PermissionKeys.BookingReadAny,
    PermissionKeys.BookingUpdateAny,
    PermissionKeys.AvailabilityReadPublic,
    PermissionKeys.GalleryRead,
    PermissionKeys.GalleryWrite,
    PermissionKeys.UploadImage,
    PermissionKeys.UserProfileRead,
    PermissionKeys.UserProfileUpdate,
  ],
  [SystemRoleKeys.Vendor]: [
    PermissionKeys.WorkspaceVendorAccess,
    PermissionKeys.VendorRead,
    PermissionKeys.VendorUpdateOwn,
    PermissionKeys.PackageVendorRead,
    PermissionKeys.PackageVendorCreateOwn,
    PermissionKeys.PackageVendorUpdateOwn,
    PermissionKeys.PackageVendorDeleteOwn,
    PermissionKeys.AvailabilityReadOwn,
    PermissionKeys.AvailabilityWriteOwn,
    PermissionKeys.BookingReadOwnVendor,
    PermissionKeys.BookingUpdateOwnVendor,
    PermissionKeys.LeadReadOwnVendor,
    PermissionKeys.LeadUpdateOwnVendor,
    PermissionKeys.LeadConvertOwnVendor,
    PermissionKeys.GalleryRead,
    PermissionKeys.GalleryWrite,
    PermissionKeys.UploadImage,
    PermissionKeys.UserProfileRead,
    PermissionKeys.UserProfileUpdate,
    PermissionKeys.ScopeVendorOwn,
  ],
  [SystemRoleKeys.Customer]: [
    PermissionKeys.WorkspaceCustomerAccess,
    PermissionKeys.AvailabilityReadPublic,
    PermissionKeys.BookingCreate,
    PermissionKeys.BookingReadOwnCustomer,
    PermissionKeys.LeadCreate,
    PermissionKeys.PackagePlatformRead,
    PermissionKeys.PackageVendorRead,
    PermissionKeys.GalleryRead,
    PermissionKeys.UserProfileRead,
    PermissionKeys.UserProfileUpdate,
    PermissionKeys.ScopeCustomerOwn,
  ],
};
